name: Run on Every Pull Request

on:
  pull_request:  # ✅ Trigger on any PR to any branch
    types: [opened, synchronize, reopened]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "👋 Hello from your GitHub Action! This ran on a PR!"
